Return-Path: <openbmc-bounces+lists+openbmc=lfdr.de@lists.ozlabs.org>
X-Original-To: lists+openbmc@lfdr.de
Delivered-To: lists+openbmc@lfdr.de
Received: from lists.ozlabs.org (lists.ozlabs.org [203.11.71.2])
	by mail.lfdr.de (Postfix) with ESMTPS id 013862195B3
	for <lists+openbmc@lfdr.de>; Thu,  9 Jul 2020 03:36:34 +0200 (CEST)
Received: from bilbo.ozlabs.org (lists.ozlabs.org [IPv6:2401:3900:2:1::3])
	by lists.ozlabs.org (Postfix) with ESMTP id 4B2Jg21YDgzDqpC
	for <lists+openbmc@lfdr.de>; Thu,  9 Jul 2020 11:36:30 +1000 (AEST)
X-Original-To: openbmc@lists.ozlabs.org
Delivered-To: openbmc@lists.ozlabs.org
Authentication-Results: lists.ozlabs.org; spf=pass (sender SPF authorized)
 smtp.mailfrom=quantatw.com (client-ip=219.87.191.90; helo=mx01.quantatw.com;
 envelope-from=prvs=4527987c0=duke.du@quantatw.com; receiver=<UNKNOWN>)
Authentication-Results: lists.ozlabs.org;
 dmarc=none (p=none dis=none) header.from=quantatw.com
Received: from mx01.quantatw.com (mx01.quantatw.com [219.87.191.90])
 by lists.ozlabs.org (Postfix) with ESMTP id 4B2Jf86Sl2zDqkq
 for <openbmc@lists.ozlabs.org>; Thu,  9 Jul 2020 11:35:36 +1000 (AEST)
IronPort-SDR: CMkTTHxx5jIHb5rSzJr0hbwFoAUSQEmGxjprehP4oJsseXzno0ZAesjIQ9k+at6pwWcuxrcTtA
 WUZIBobmtTwA==
Received: from unknown (HELO mailbx09.quanta.corp) ([10.243.91.106])
 by mx01.quantatw.com with ESMTP; 09 Jul 2020 09:35:30 +0800
Received: from mailbx12.quanta.corp (10.243.91.109) by mailbx09.quanta.corp
 (10.243.91.106) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id 15.1.1713.5; Thu, 9 Jul 2020
 09:35:26 +0800
Received: from mailbx12.quanta.corp ([fe80::3581:3a50:e90e:3a05]) by
 mailbx12.quanta.corp ([fe80::3581:3a50:e90e:3a05%4]) with mapi id
 15.01.1713.009; Thu, 9 Jul 2020 09:35:26 +0800
From: =?utf-8?B?RHVrZSBEdSAo5p2c56Wl5ZiJKQ==?= <Duke.Du@quantatw.com>
To: Matt Spinler <mspinler@linux.ibm.com>, "openbmc@lists.ozlabs.org"
 <openbmc@lists.ozlabs.org>
Subject: RE: Sensor value is not accurate which is generated by phosphor-hwmon
Thread-Topic: Sensor value is not accurate which is generated by phosphor-hwmon
Thread-Index: AdZUBEn/4Ej+yY+STCqqh8lBBuS3/QAP2wuAADQFxIAAHyyNQA==
Date: Thu, 9 Jul 2020 01:35:25 +0000
Message-ID: <0d371cd70b5a46d4814a1e306d8b0152@quantatw.com>
References: <07175a7434c44797944ff8550006abbe@quantatw.com>
 <07cbefdd-1768-91f2-37af-0918627b1f5b@linux.ibm.com>
 <1e29f5ac-8c97-3329-aeed-bf7c79eda7af@linux.ibm.com>
In-Reply-To: <1e29f5ac-8c97-3329-aeed-bf7c79eda7af@linux.ibm.com>
Accept-Language: en-US, zh-TW
Content-Language: zh-TW
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: 
x-originating-ip: [10.243.91.252]
x-tm-snts-smtp: A3A03F8483E1FE796E09428414D974DBBEAC5E68784FEB0645C5D735A717A51A2000:8
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
MIME-Version: 1.0
X-BeenThere: openbmc@lists.ozlabs.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: Development list for OpenBMC <openbmc.lists.ozlabs.org>
List-Unsubscribe: <https://lists.ozlabs.org/options/openbmc>,
 <mailto:openbmc-request@lists.ozlabs.org?subject=unsubscribe>
List-Archive: <http://lists.ozlabs.org/pipermail/openbmc/>
List-Post: <mailto:openbmc@lists.ozlabs.org>
List-Help: <mailto:openbmc-request@lists.ozlabs.org?subject=help>
List-Subscribe: <https://lists.ozlabs.org/listinfo/openbmc>,
 <mailto:openbmc-request@lists.ozlabs.org?subject=subscribe>
Cc: =?utf-8?B?RWRkaWUgTHUgKOmZuOWuh+WyoSk=?= <Eddie.Lu@quantatw.com>,
 =?utf-8?B?RnJhbiBIc3UgKOW+kOiqjOismSk=?= <Fran.Hsu@quantatw.com>,
 =?utf-8?B?R2VvcmdlIEh1bmcgKOa0quW/oOaVrCk=?= <George.Hung@quantatw.com>
Errors-To: openbmc-bounces+lists+openbmc=lfdr.de@lists.ozlabs.org
Sender: "openbmc" <openbmc-bounces+lists+openbmc=lfdr.de@lists.ozlabs.org>

SGkgTWF0dCwNCg0KICBTb3JyeSBmb3IgbGF0ZSwgSSB3aWxsIHRyeSB0aGlzIGNvbW1pdCBpbiBv
dXIgcHJvamVjdCwgaXQgbG9va3MgZ29vZCB0byBtZSwgdGhhbmtzIGZvciB5b3VyIGhlbHAuDQoN
CnRoYW5rcw0KRHVrZQ0KPiAtLS0tLU9yaWdpbmFsIE1lc3NhZ2UtLS0tLQ0KPiBGcm9tOiBNYXR0
IFNwaW5sZXIgPG1zcGlubGVyQGxpbnV4LmlibS5jb20+DQo+IFNlbnQ6IFRodXJzZGF5LCBKdWx5
IDksIDIwMjAgMjozOCBBTQ0KPiBUbzogRHVrZSBEdSAo5p2c56Wl5ZiJKSA8RHVrZS5EdUBxdWFu
dGF0dy5jb20+OyBvcGVuYm1jQGxpc3RzLm96bGFicy5vcmcNCj4gQ2M6IEVkZGllIEx1ICjpmbjl
roflsqEpIDxFZGRpZS5MdUBxdWFudGF0dy5jb20+OyBGcmFuIEhzdSAo5b6Q6KqM6KyZKQ0KPiA8
RnJhbi5Ic3VAcXVhbnRhdHcuY29tPjsgR2VvcmdlIEh1bmcgKOa0quW/oOaVrCkNCj4gPEdlb3Jn
ZS5IdW5nQHF1YW50YXR3LmNvbT4NCj4gU3ViamVjdDogUmU6IFNlbnNvciB2YWx1ZSBpcyBub3Qg
YWNjdXJhdGUgd2hpY2ggaXMgZ2VuZXJhdGVkIGJ5DQo+IHBob3NwaG9yLWh3bW9uDQo+IA0KPiAN
Cj4gDQo+IE9uIDcvNy8yMDIwIDEyOjQ4IFBNLCBNYXR0IFNwaW5sZXIgd3JvdGU6DQo+ID4NCj4g
Pg0KPiA+IE9uIDcvNi8yMDIwIDk6MTUgUE0sIER1a2UgRHUgKOadnOelpeWYiSkgd3JvdGU6DQo+
ID4+DQo+ID4+IEhpIEFsbCwNCj4gPj4NCj4gPj4gwqAgSSBmb3VuZCBzZW5zb3IgdmFsdWUgdHlw
ZSBpcyBjaGFuZ2VkIHRvIGRvdWJsZSBpbg0KPiA+Pg0KPiA+PiB4eXovb3BlbmJtY19wcm9qZWN0
L1NlbnNvci9WYWx1ZS5pbnRlcmZhY2UueWFtbCwNCj4gPj4NCj4gPj4gYWZ0ZXIgdGhpcyBjaGFu
Z2UsIHRoZSBzZW5zb3IgdmFsdWUgb24gdGhlIGludGVyZmFjZQ0KPiA+Pg0KPiA+PiB4eXoub3Bl
bmJtY19wcm9qZWN0LlNlbnNvci5WYWx1ZSB3aGljaCBpcyBnZW5lcmF0ZWQgYnkNCj4gPj4NCj4g
Pj4gcGhvc3Bob3ItaHdtb24gaXMgbm90IGFjY3VyYXRlLCBmb3IgZXhhbXBsZSwgMC45OSB2b2x0
cw0KPiA+Pg0KPiA+PiB3b3VsZCBiZSByZWNvcmQgMCB2b2x0cyBvbiB0aGUgaW50ZXJmYWNlLiBE
byBJIG1pc3Mgc29tZQ0KPiA+Pg0KPiA+PiBjb25maWd1cmF0aW9uIGZvciBwaG9zcGhvci1od21v
biA/DQo+ID4+DQo+ID4NCj4gPiBMb29rcyBsaWtlIHRoYXQgaXMgaW5kZWVkIGEgcHJvYmxlbS7C
oCBJIGhhdmVuJ3QgbG9va2VkIGNsb3NlbHkgeWV0LA0KPiA+IGJ1dCBJIHdvbmRlciBpZiBob3cg
dGhlIGNvZGUgaXMgYXR0ZW1wdGluZyB0byBzdXBwb3J0IFNlbnNvci5WYWx1ZSBhcw0KPiA+IGJv
dGggYW4gaW50NjQgYW5kIGEgZG91YmxlIGF0IHRoZSBzYW1lIHRpbWUgaGFzIGFuIGlzc3VlLg0K
PiA+DQo+ID4gTWF5YmUgbm93IHdvdWxkIGJlIGEgZ29vZCB0aW1lIHRvIGp1c3Qgc3VwcG9ydCB0
aGUgZG91YmxlIHZlcnNpb24uDQo+ID4gSSBjYW4gdGFrZSBhIGxvb2suDQo+IA0KPiBodHRwczov
L2dlcnJpdC5vcGVuYm1jLXByb2plY3QueHl6L2Mvb3BlbmJtYy9waG9zcGhvci1od21vbi8rLzM0
NDgxDQo+IA0KPiA+DQo+ID4+IFNlbnNvciB2YWx1ZSB0eXBlIGlzIGNoYW5nZWQgdG8gZG91Ymxl
LCB3aGljaCBjb21taXQgaXMgOg0KPiA+Pg0KPiA+PiA0ZWM2NTg3ZmE5MDhmZTlkZjQxY2MwOTYy
YWI2ZmY2NDQ2ZmJkNTRmDQo+ID4+DQo+IGh0dHBzOi8vZ2l0aHViLmNvbS9vcGVuYm1jL3Bob3Nw
aG9yLWRidXMtaW50ZXJmYWNlcy9jb21taXQvNGVjNjU4N2ZhOQ0KPiA+PiAwOGZlOWRmNDFjYzA5
NjJhYjZmZjY0NDZmYmQ1NGYNCj4gPj4NCj4gPj4NCj4gPj4gVGhhbmtzLg0KPiA+Pg0KPiA+PiBE
dWtlIER1DQo+ID4+DQo+ID4NCg0K
